export const siteConfig = {
  name: "Lets Go Travel SS",
  description: "Tu agencia de viajes premium en Ecuador, especializada en experiencias personalizadas a Sudamérica, Europa y más allá.",
  mainNav: [
    {
      title: "Inicio",
      href: "/",
    },
        {
      title: "Sobre Nosotros",
      href: "/about",
    },
        {
      title: "Contacto",
      href: "/contact",
    },
    {
      title: "Destinos",
      href: "/destinations",
    },
    {
      title: "Servicios",
      href: "/services",
    },
    {
      title: "Financiamiento",
      href: "/financing",
    },
  ],
  links: {
    instagram: "https://instagram.com/letsgotravel",
    facebook: "https://facebook.com/letsgotravel",
    tiktok: "https://tiktok.com/@letsgotravel",
  },
  contact: {
    phone: "+593 999880033",
    email: "letssgotravel@protonmail.com",
    whatsapp: "+593999880033",
    address: "Av. Eloy Alfaro y Fernando Ayarza, Quito, Ecuador",
  },
  destinations: [
    {
      id: "southamerica",
      name: "Sudamérica",
      locations: [
        {
          id: "galapagos",
          name: "Islas Galapagos",
          country: "Ecuador",
          description: "Explora la fauna única y las playas vírgenes de las islas encantadas.",
          price: 1200,
          image: "https://images.pexels.com/photos/601174/pexels-photo-601174.jpeg",
          duration: "7 días",
        },
        {
          id: "machu-picchu",
          name: "Machu Picchu",
          country: "Peru",
          description: "Descubre la antigua ciudadela inca enclavada en los Andes..",
          price: 950,
          image: "https://images.pexels.com/photos/2539444/pexels-photo-2539444.jpeg",
          duration: "5 días",
        },
        {
          id: "amazon",
          name: "Selva Amazónica",
          country: "Ecuador",
          description: "Sumérgete en la selva tropical más grande del mundo y su biodiversidad.",
          price: 800,
          image: "https://images.pexels.com/photos/2739664/pexels-photo-2739664.jpeg",
          duration: "4 días",
        },
      ],
    },
    {
      id: "europe",
      name: "Europa",
      locations: [
        {
          id: "paris",
          name: "Paris",
          country: "Francia",
          description: "Vive el romance y la riqueza cultural de la Ciudad de la Luz.",
          price: 1500,
          image: "https://images.pexels.com/photos/739407/pexels-photo-739407.jpeg",
          duration: "6 días",
        },
        {
          id: "santorini",
          name: "Santorini",
          country: "Grecia",
          description: "Relájate en esta hermosa isla volcánica con sus icónicas iglesias de cúpulas azules.",
          price: 1400,
          image: "https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg",
          duration: "5 días",
        },
        {
          id: "rome",
          name: "Roma",
          country: "Italia",
          description: "Camina por la historia en la ciudad eterna y sus monumentos antiguos.",
          price: 1300,
          image: "https://images.pexels.com/photos/1701595/pexels-photo-1701595.jpeg",
          duration: "6 días",
        },
      ],
    },
    {
      id: "caribbean",
      name: "Caribe",
      locations: [
        {
          id: "punta-cana",
          name: "Punta Cana",
          country: "República Dominicana",
          description: "Disfruta de playas blancas vírgenes y resorts todo incluido.",
          price: 1100,
          image: "https://images.pexels.com/photos/1174732/pexels-photo-1174732.jpeg",
          duration: "7 días",
        },
        {
          id: "cancun",
          name: "Cancún",
          country: "México",
          description: "Vive aguas turquesas y una vida nocturna vibrante en la Riviera Maya.",
          price: 1050,
          image: "https://images.pexels.com/photos/1802255/pexels-photo-1802255.jpeg",
          duration: "6 días",
        },
      ],
    },
  ],
  services: [
    {
      id: "personalized",
      title: "Itinerarios Personalizados",
      description: "Creamos experiencias de viaje hechas a medida según tus preferencias y presupuesto.",
      icon: "Sparkles",
    },
    {
      id: "visas",
      title: "Tramitación de Visas",
      description: "Asistencia experta en solicitudes de visa y documentación para cualquier destino.",
      icon: "FileCheck",
    },
    {
      id: "insurance",
      title: "Seguro de Viaje",
      description: "Opciones completas de seguro para protegerte durante tu aventura.",
      icon: "Shield",
    },
    {
      id: "groups",
      title: "Viajes Grupales",
      description: "Únete a nuestros tours guiados a destinos populares con tarifas especiales.",
      icon: "Users",
    },
    {
      id: "transfers",
      title: "Traslados al Aeropuerto",
      description: "Transporte cómodo y confiable desde el aeropuerto a tu alojamiento.",
      icon: "Car",
    },
    {
      id: "assistance",
      title: "Asistencia 24/7",
      description: "Soporte las 24 horas durante todo tu viaje para tu tranquilidad.",
      icon: "HeadsetIcon",
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "María Gonzalez",
      location: "Quito, Ecuador",
      testimonial: "Let's Go Travel hizo que nuestro viaje familiar a Europa fuera inolvidable. ¡Cada detalle estuvo perfectamente organizado!",
      image: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",
      rating: 5,
    },
    {
      id: 2,
      name: "Carlos Mendoza",
      location: "Guayaquil, Ecuador",
      testimonial: "La atención personalizada y la calidad de los servicios superaron nuestras expectativas. ¡Altamente recomendado!",
      image: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg",
      rating: 5,
    },
    {
      id: 3,
      name: "Ana Paredes",
      location: "Cuenca, Ecuador",
      testimonial: "Gracias a sus opciones de financiamiento, pudimos cumplir el sueño de visitar las Islas Galápagos.",
      image: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
      rating: 5,
    },
  ],
  banks: [
    { name: "Banco Pichincha", logo: "/banks/pichincha.png" },
    { name: "Produbanco", logo: "/banks/produbanco.png" },
    { name: "Banco Guayaquil", logo: "/banks/guayaquil.png" },
    { name: "Banco del Pacífico", logo: "/banks/pacifico.png" },
  ],
  seals: [
    { name: "IATA", logo: "/seals/iata.png" },
    { name: "Ministerio de Turismo", logo: "/seals/mintur.png" },
    { name: "Cámara de Turismo", logo: "/seals/camtur.png" },
  ],
};