export const siteConfig = {
  name: "Lets Go Travel & SS",
  description: "Tu agencia de viajes premium en Ecuador, especializada en experiencias personalizadas a Sudamérica, Europa y más allá.",
  mainNav: [
    {
      title: "Inicio",
      href: "/",
    },
        {
      title: "Sobre Nosotros",
      href: "/about",
    },
        {
      title: "Contacto",
      href: "/contact",
    },
    {
      title: "Destinos",
      href: "/destinations",
    },
    {
      title: "Servicios",
      href: "/services",
    },
    {
      title: "Financiamiento",
      href: "/financing",
    },
  ],
  links: {
    instagram: "https://www.instagram.com/letsgotravel_ss/",
    facebook: "https://www.facebook.com/lets.travelss",
    tiktok: "https://www.tiktok.com/@lets_go_travel_ss",
  },
  contact: {
    phone: "+593 999497250",
    email: "info@letsgotravelss.com",
    whatsapp: "+593999497250",
    address: "Av. Eloy Alfaro y Fernando Ayarza, Quito, Ecuador",
  },
  destinations: [
    {
      id: "southamerica",
      name: "Sudamérica",
      locations: [
        {
          id: "galapagos",
          name: "Islas Galapagos",
          country: "Ecuador",
          description: "Explora la fauna única y las playas vírgenes de las islas encantadas.",
          price: 1200,
          image: "https://images.pexels.com/photos/601174/pexels-photo-601174.jpeg",
          duration: "7 días",
        },
        {
          id: "machu-picchu",
          name: "Machu Picchu",
          country: "Peru",
          description: "Descubre la antigua ciudadela inca enclavada en los Andes..",
          price: 950,
          image: "https://images.pexels.com/photos/2539444/pexels-photo-2539444.jpeg",
          duration: "5 días",
        },
        {
          id: "amazon",
          name: "Selva Amazónica",
          country: "Ecuador",
          description: "Sumérgete en la selva tropical más grande del mundo y su biodiversidad.",
          price: 800,
          image: "https://images.pexels.com/photos/2739664/pexels-photo-2739664.jpeg",
          duration: "4 días",
        },
      ],
    },
    {
      id: "europe",
      name: "Europa",
      locations: [
        {
          id: "paris",
          name: "Paris",
          country: "Francia",
          description: "Vive el romance y la riqueza cultural de la Ciudad de la Luz.",
          price: 1500,
          image: "https://images.pexels.com/photos/739407/pexels-photo-739407.jpeg",
          duration: "6 días",
        },
        {
          id: "santorini",
          name: "Santorini",
          country: "Grecia",
          description: "Relájate en esta hermosa isla volcánica con sus icónicas iglesias de cúpulas azules.",
          price: 1400,
          image: "https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg",
          duration: "5 días",
        },
        {
          id: "rome",
          name: "Roma",
          country: "Italia",
          description: "Camina por la historia en la ciudad eterna y sus monumentos antiguos.",
          price: 1300,
          image: "https://images.pexels.com/photos/1701595/pexels-photo-1701595.jpeg",
          duration: "6 días",
        },
      ],
    },
    {
      id: "caribbean",
      name: "Caribe",
      locations: [
        {
          id: "punta-cana",
          name: "Punta Cana",
          country: "República Dominicana",
          description: "Disfruta de playas blancas vírgenes y resorts todo incluido.",
          price: 1100,
          image: "https://images.pexels.com/photos/1174732/pexels-photo-1174732.jpeg",
          duration: "7 días",
        },
        {
          id: "cancun",
          name: "Cancún",
          country: "México",
          description: "Vive aguas turquesas y una vida nocturna vibrante en la Riviera Maya.",
          price: 1050,
          image: "https://images.pexels.com/photos/1802255/pexels-photo-1802255.jpeg",
          duration: "6 días",
        },
      ],
    },
  ],
  services: [
    {
      id: "personalized",
      title: "Itinerarios Personalizados",
      description: "Creamos experiencias de viaje hechas a medida según tus preferencias y presupuesto.",
      icon: "Sparkles",
    },
    {
      id: "visas",
      title: "Tramitación de Visas",
      description: "Asistencia experta en solicitudes de visa y documentación para cualquier destino.",
      icon: "FileCheck",
    },
    {
      id: "insurance",
      title: "Seguro de Viaje",
      description: "Opciones completas de seguro para protegerte durante tu aventura.",
      icon: "Shield",
    },
    {
      id: "groups",
      title: "Viajes Grupales",
      description: "Únete a nuestros tours guiados a destinos populares con tarifas especiales.",
      icon: "Users",
    },
    {
      id: "transfers",
      title: "Traslados al Aeropuerto",
      description: "Transporte cómodo y confiable desde el aeropuerto a tu alojamiento.",
      icon: "Car",
    },
    {
      id: "assistance",
      title: "Asistencia 24/7",
      description: "Soporte las 24 horas durante todo tu viaje para tu tranquilidad.",
      icon: "HeadsetIcon",
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "Esteban Enriquez",
      location: "Quito, Ecuador",
      testimonial: "Viajamos en pareja a Panamá durante 4 días y 3 noches y tuvimos una muy buena experiencia. Conocimos el Canal de Panamá, recorrimos varios centros comerciales y disfrutamos mucho de la ciudad.",
      rating: 4,
    },
    {
      id: 2,
      name: "Bryan Ontaneda",
      location: "Loja, Ecuador",
      testimonial: "Realizamos un viaje a Italia de carácter religioso y contamos con el acompañamiento de Let's Go Travel durante todo el proceso. Nos ayudaron con la gestión del visado, la organización del viaje y el hospedaje en destino, facilitándonos cada etapa para que pudiéramos viajar con tranquilidad. La atención y el seguimiento fueron muy buenos y la experiencia resultó muy especial para nosotros.",
      rating: 5,
    },
    {
      id: 3,
      name: "Viviana Sinchiguano",
      location: "Malaga, España",
      testimonial: "Viajé desde Málaga, España, a Quito para disfrutar de mis vacaciones y fue una experiencia increíble. Durante mi estancia pude conocer lugares emblemáticos como el Cotopaxi, la Mitad del Mundo y el Centro Histórico de Quito, además de otros atractivos turísticos. La organización del viaje me permitió aprovechar muy bien cada día y descubrir diferentes rincones de Ecuador. Me llevo recuerdos maravillosos de este viaje.",
      rating: 4,
    },
    {
      id: 4,
      name: "Paola Calvache",
      location: "Quito, Ecuador",
      testimonial: "Viajamos en familia a Galápagos y fue una experiencia increíble. Tuvimos la oportunidad de conocer las islas Santa Cruz y San Cristóbal, realizar varias excursiones y disfrutar de paisajes realmente únicos. Todo el viaje fue muy especial, desde las actividades hasta la comida y los momentos compartidos en familia. Nos llevamos recuerdos maravillosos de Galápagos y disfrutamos muchísimo cada día.",
      rating: 4,
    },

  ],
  banks: [
    { name: "Banco Pichincha", logo: "/banks/pichincha.png" },
    { name: "Produbanco", logo: "/banks/produbanco.png" },
    { name: "Banco Guayaquil", logo: "/banks/guayaquil.png" },
    { name: "Banco del Pacífico", logo: "/banks/pacifico.png" },
  ],
  seals: [
    { name: "IATA", logo: "/seals/iata.png" },
    { name: "Ministerio de Turismo", logo: "/seals/mintur.png" },
    { name: "Cámara de Turismo", logo: "/seals/camtur.png" },
  ],
};